name: Deploy dev
on:
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Клонируем репозиторий
      - name: Checkout
        uses: actions/checkout@v2

      # Собираем Docker-образ и сохраняем его в файл
      - name: Build Docker image
        run: docker build -t loan-dev . --build-arg port=3001
        shell: bash

      # Сохраняем Docker-образ в архив
      - name: Save Docker image to archive
        run: docker save loan-dev -o loan-dev.tar
        shell: bash

      # Копируем архив с Docker-образом на сервер
      - name: Copy Docker image archive to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: loan-dev.tar
          target: /tmp

      # Распаковываем архив с Docker-образом на сервере
      - name: Extract Docker image from archive on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker load --input /tmp/loan-dev.tar

      # Удаляем архив с Docker-образом на сервере
      - name: Remove Docker image archive on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            rm /tmp/loan-dev.tar

      # Запускаем Docker-контейнер на сервере
      - name: Run Docker container on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker stop loan-dev || true
            docker rm loan-dev || true
            docker run --name loan-dev -p 3001:3001 -d --restart unless-stopped loan-dev
